---
title: "Homework7"
author: "Sam Troast"
date: "2025-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```
**Question 1**
-
```{r}
data(iris)
view(iris)
# The iris dataset has 150 observations and 5 variables.
```

**Question 2**
-
```{r}
iris1 <- iris%>%
  filter(Species %in% c("virginica","versicolor"), Sepal.Length > 6.0, Sepal.Width > 2.5)

view(iris1)

# There are 56 observations and 3 variables in the iris1 dataset.
```

**Question 3**
-
```{r}
iris2 <- iris1 %>%
  select("Species", "Sepal.Length", "Sepal.Width")

# There are 56 observations and 3 variables in the iris2 dataset.
```

**Question 4**
-
```{r}
iris3 <- iris2 %>%
  arrange(by=Sepal.Length)

head(iris3)
```

**Question 5**
-
```{r}
iris4 <- iris3 %>%
  mutate(Sepal.Area=Sepal.Length*Sepal.Width)

iris4
```

**Question 6**
-
```{r}
iris5 <- iris4 %>%
  summarize(AvgSepalLength=mean(Sepal.Length), AvgSepalWidth=mean(Sepal.Width), SampleSize=n())

print(iris5)
```

**Question 7**
-
```{r}
iris6 <- iris4%>%
  group_by(Species) %>%
  summarize(Avg.Sepal.Length=mean(Sepal.Length),Avg.Sepal.Width=mean(Sepal.Width),Sample.Size=n())

print(iris6)
```

**Question 8**
-
```{r}
irisFinal<- iris%>%
  filter(Species %in% c("virginica","versicolor"), Sepal.Length > 6.0, Sepal.Width > 2.5)%>% 
  select("Species","Sepal.Length","Sepal.Width")%>% 
  arrange(by=Sepal.Length)%>% 
  mutate(Sepal.Area=Sepal.Length*Sepal.Width)%>% 
  group_by(Species) %>% 
  summarize(Avg.Sepal.Length=mean(Sepal.Length),Avg.Sepal.Width=mean(Sepal.Width),Sample.Size=n()) 

print(irisFinal)
```
**Question 9**
-
```{r}
Bigdataset <- iris %>%
    pivot_longer(col=Sepal.Length:Petal.Width, names_to= "Measure", values_to = "Value")

print(Bigdataset)
```
